<?php

namespace App\Filament\Resources\CompiledResults\Schemas;

use App\Filament\Support\SchoolSelect;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class CompiledResultForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                Section::make('Compiled result')
                    ->description('These values are generated by Compile Results. Edit only when correcting a reviewed result.')
                    ->schema([
                        SchoolSelect::make(),
                        Select::make('exam_id')->relationship('exam', 'name')->searchable()->preload()->required(),
                        Select::make('student_id')->relationship('student', 'admission_number')->searchable()->preload()->required(),
                        Select::make('subject_id')->relationship('subject', 'name')->searchable()->preload()->required(),
                        TextInput::make('total_score')->numeric()->required()->prefix('Score'),
                        TextInput::make('grade')->maxLength(10),
                        TextInput::make('grade_point')->numeric(),
                        TextInput::make('remark')->maxLength(255),
                        TextInput::make('position')->numeric(),
                        Select::make('status')->required()->default('compiled')->options([
                            'compiled' => 'Compiled',
                            'reviewed' => 'Reviewed',
                            'published' => 'Published',
                        ]),
                    ])
                    ->columns(2),
            ]);
    }
}
