<?php

namespace App\Http\Controllers;

use App\Models\School;
use App\Support\CurrentDivision;
use Illuminate\Http\Request;

/**
 * Landing point for signed links generated by School::portalUrl() — a
 * parent-notification email, WhatsApp reminder, or credential email always
 * knows a specific division when the link is generated, but the shared
 * subdomain (one per client school, not per division) has no way to carry
 * that in the URL itself. This pre-seeds the division into session before
 * handing off into the normal portal flow, so the visitor lands directly in
 * the right division's context instead of hitting the division picker.
 *
 * The signature proves the link is genuine, not that the current visitor is
 * authorized — CurrentDivision::get()'s own re-validation against the
 * authenticated user's actual access is what enforces that.
 */
class PortalDivisionLinkController extends Controller
{
    public function __invoke(Request $request)
    {
        abort_unless($request->hasValidSignature(), 403);

        $parent = School::query()
            ->withoutGlobalScope('school-panel-current-tenant')
            ->findOrFail($request->integer('school'));

        $division = School::query()
            ->withoutGlobalScope('school-panel-current-tenant')
            ->findOrFail($request->integer('division'));

        session([CurrentDivision::sessionKeyFor($parent) => $division->getKey()]);

        $scheme = parse_url((string) config('app.url'), PHP_URL_SCHEME) ?: 'https';
        $domain = config('app.central_domain');
        $redirect = (string) $request->query('redirect', '');

        return redirect()->to("{$scheme}://{$parent->slug}.{$domain}/portal{$redirect}");
    }
}
